services:
  net_monitor_analysis_system-collector-1:
    image: net_monitor_analysis_system_collector:0.1
    container_name: net_monitor_analysis_system_collector-1
    restart: none
    ports:
      - 9401:9400
    networks:
      v-network:
        ipv4_address: 192.168.2.1
    environment:
      - SERVER_IP=162.105.146.22    # 各个其他服务的 host ip 地址, redis 以及 doris 等
      - SERVICE_IP=10.7.234.150     # 本机地址用于服务注册，如果外部要访问需要公有 ip
      - SERVICE_PORT=9401           # 本机端口用于服务注册
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
  net_monitor_analysis_system-collector-2:
    image: net_monitor_analysis_system_collector:0.1
    container_name: net_monitor_analysis_system_collector-2
    restart: none
    ports:
      - 9402:9400
    networks:
      v-network:
        ipv4_address: 192.168.2.2
    environment:
      - SERVER_IP=162.105.146.22    # 各个其他服务的 host ip 地址, redis 以及 doris 等
      - SERVICE_IP=10.7.234.150     # 本机地址用于服务注册，如果外部要访问需要公有 ip
      - SERVICE_PORT=9402           # 本机端口用于服务注册
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
  net_monitor_analysis_system-collector-3:
    image: net_monitor_analysis_system_collector:0.1
    container_name: net_monitor_analysis_system_collector-3
    restart: none
    ports:
      - 9403:9400
    networks:
      v-network:
        ipv4_address: 192.168.2.3
    environment:
      - SERVER_IP=162.105.146.22    # 各个其他服务的 host ip 地址, redis 以及 doris 等
      - SERVICE_IP=10.7.234.150     # 本机地址用于服务注册，如果外部要访问需要公有 ip
      - SERVICE_PORT=9403           # 本机端口用于服务注册
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G
networks:
  v-network:
    external: true