spring:
  application:
    name: net_monitor_analysis_system
  kafka:
    bootstrap-servers: localhost:19092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: none
    template:
      default-topic: topic_name # update this

logging:
  level:
    root: info

collector:
  port: 9400
  kafka:
    topic: collected-monitor-data-test

kafka-test:
  topic: test-topic