spring:
  application:
    name: net_monitor_analysis_system
  profiles:
    active: test
  kafka:
    bootstrap-servers: ${SERVER_IP:162.105.146.22}:19092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: none
    template:
      default-topic: topic_name # update this
  data:
    redis:
      host: ${SERVER_IP:162.105.146.22}
      database: 0
      port: 6379

datasource:
  doris:
    jdbc-url: jdbc:mysql://${SERVER_IP:162.105.146.22}:9031/net_analysis
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    root: info

collector:
  port: 9400
  kafka:
    topic: collected-monitor-data-test

kafka-test:
  topic: test-topic

kafka-topic:
  collect-complete: collect-complete

nacos:
  discovery:
    server-addr: ${SERVER_IP:162.105.146.22}:8848
    namespace: public
    group-name: DEFAULT_GROUP
    service-name: net_monitor_analysis_system_collector
    ip: ${SERVICE_IP:10.7.234.150}
    port: ${SERVICE_PORT:9400}

